import { useCallback, useRef } from 'react';
import JSZip from 'jszip';
import { capturePageAsImage, injectNavigation, pageFileName } from '../aiService.js';
import { htmlToReactComponent, htmlToTailwind, htmlToCleanHtml } from '../codeExport.js';
import { generateAllWireframes } from '../components/PlanPreview.jsx';
import { generateId } from './useProjects.js';

// ── Helpers ──

/** Wrap an export operation with consistent error handling */
function safeExport(label, fn) {
  try {
    const result = fn();
    return result; // may be a Promise for async functions
  } catch (err) {
    console.error(`[ProtoAI] ${label} failed:`, err);
    alert(`${label}失败：${err.message || '未知错误'}`);
  }
}

async function safeExportAsync(label, fn) {
  try {
    await fn();
  } catch (err) {
    console.error(`[ProtoAI] ${label} failed:`, err);
    alert(`${label}失败：${err.message || '未知错误'}`);
  }
}

/** Validate imported project structure */
function validateProjectSchema(data) {
  if (!data || typeof data !== 'object') return '文件内容不是有效的 JSON 对象';
  if (data.type !== 'protoai_project') return '文件类型不正确，请选择 .protoai.json 文件';
  if (!data.project || typeof data.project !== 'object') return '缺少项目数据';

  const proj = data.project;
  if (typeof proj.name !== 'string' && proj.name !== undefined) return '项目名称格式不正确';
  if (proj.pages && !Array.isArray(proj.pages)) return 'pages 字段格式不正确';
  if (proj.history && !Array.isArray(proj.history)) return 'history 字段格式不正确';
  if (proj.savedPlans && !Array.isArray(proj.savedPlans)) return 'savedPlans 字段格式不正确';

  return null; // valid
}

export default function useExport({
  currentProject, projectName, pages, pagesRef, generatedHtml, currentPageIndex,
  setProjects, setActiveProjectId, setPages,
  setCurrentPageIndex, setCode, setMessages,
  setPlannedPages, setPlannedStyleSpec, setDetectedPlatform,
  setPcPages, setMobilePages, setActivePlanPlatform,
  setPcGeneratedPages, setMobileGeneratedPages,
  setWireframeHtmls, setRightViewMode,
  setGenerateProgress, setGenerateError,
  setIsGenerating, setIsRefining, setIsRegenerating,
}) {
  const importInputRef = useRef(null);

  // ── Export current page HTML ──

  const handleExport = useCallback(() => {
    safeExport('导出 HTML', () => {
      if (!generatedHtml) return;
      const page = pages[currentPageIndex];
      const fileName = page?.name ? `${projectName || 'prototype'}_${page.name}.html` : `${projectName || 'prototype'}.html`;
      const blob = new Blob([generatedHtml], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = fileName; a.click();
      URL.revokeObjectURL(url);
    });
  }, [generatedHtml, projectName, pages, currentPageIndex]);

  // ── Export all pages as ZIP ──

  const handleExportAll = useCallback(async () => {
    await safeExportAsync('导出 ZIP', async () => {
      const validPages = pages.filter((p) => p?.html);
      if (validPages.length === 0) return;
      if (validPages.length === 1) { handleExport(); return; }

      const pagesWithNav = injectNavigation(validPages);
      const zip = new JSZip();
      pagesWithNav.forEach((page, i) => {
        if (!page?.html) return;
        zip.file(pageFileName(page, i), page.html);
      });

      const pageLinks = pages.map((page, i) => {
        if (!page?.html) return '';
        const fn = pageFileName(page, i);
        return `<a href="${fn}" class="l"><span class="n">${page.name}</span>${page.description ? `<span class="d">${page.description}</span>` : ''}<span class="a">&rarr;</span></a>`;
      }).filter(Boolean).join('\n');

      const indexHtml = `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${projectName || 'ProtoAI Prototype'}</title><style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#fafafa;color:#111;padding:48px 24px}.c{max-width:640px;margin:0 auto}h1{font-size:28px;font-weight:700;margin-bottom:8px}p{font-size:14px;color:#888;margin-bottom:32px}.l{display:flex;align-items:center;gap:12px;padding:16px 20px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;text-decoration:none;color:#111;margin-bottom:8px;transition:all .15s}.l:hover{border-color:#1863dc;background:#f0f5ff}.n{font-weight:600;font-size:15px;flex-shrink:0}.d{flex:1;font-size:13px;color:#888;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.a{color:#ccc;font-size:18px;flex-shrink:0}.f{margin-top:48px;font-size:12px;color:#bbb;text-align:center}</style></head><body><div class="c"><h1>${projectName || 'ProtoAI Prototype'}</h1><p>共 ${validPages.length} 个页面</p>${pageLinks}<div class="f">Generated by ProtoAI</div></div></body></html>`;
      zip.file('index.html', indexHtml);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `${projectName || 'prototype'}.zip`; a.click();
      URL.revokeObjectURL(url);
    });
  }, [pages, projectName, handleExport]);

  // ── Export current page as image ──

  const handleExportImage = useCallback(async () => {
    if (!generatedHtml) return;
    await safeExportAsync('导出图片', async () => {
      setGenerateProgress('正在生成图片...');
      const blob = await capturePageAsImage(generatedHtml, 1440, 900);
      const page = pages[currentPageIndex];
      const fileName = page?.name ? `${projectName || 'prototype'}_${page.name}.png` : `${projectName || 'prototype'}.png`;
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = fileName; a.click();
      URL.revokeObjectURL(url);
      setGenerateProgress('');
    });
  }, [generatedHtml, projectName, pages, currentPageIndex, setGenerateProgress]);

  // ── Export all pages as images ZIP ──

  const handleExportAllImages = useCallback(async () => {
    await safeExportAsync('导出图片 ZIP', async () => {
      const validPages = pages.map((p, i) => ({ page: p, originalIndex: i })).filter(({ page }) => page?.html);
      if (validPages.length === 0) return;
      if (validPages.length === 1) { await handleExportImage(); return; }

      setGenerateProgress('正在生成图片...');
      const zip = new JSZip();

      for (let i = 0; i < validPages.length; i++) {
        setGenerateProgress(`正在生成图片 ${i + 1}/${validPages.length}...`);
        try {
          const blob = await capturePageAsImage(validPages[i].page.html, 1440, 900);
          const arrayBuf = await blob.arrayBuffer();
          zip.file(pageFileName(validPages[i].page, validPages[i].originalIndex).replace('.html', '.png'), arrayBuf);
        } catch (err) {
          console.warn(`Failed to capture page ${validPages[i].page.name}:`, err);
        }
      }

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `${projectName || 'prototype'}_images.zip`; a.click();
      URL.revokeObjectURL(url);
      setGenerateProgress('');
    });
  }, [pages, projectName, handleExportImage, setGenerateProgress]);

  // ── Export from history ──

  const handleExportHistory = useCallback(async (entry, type) => {
    await safeExportAsync('导出历史记录', async () => {
      if (!entry?.pages) return;
      const validPages = entry.pages.filter((p) => p?.html);
      if (validPages.length === 0) return;

      if (type === 'html' && validPages.length === 1) {
        const blob = new Blob([validPages[0].html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `${entry.description || 'prototype'}.html`; a.click();
        URL.revokeObjectURL(url);
        return;
      }

      const zip = new JSZip();
      const pagesWithNav = injectNavigation(validPages);
      pagesWithNav.forEach((page, i) => {
        if (!page?.html) return;
        zip.file(pageFileName(page, i), page.html);
      });
      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `${entry.description || 'prototype'}.zip`; a.click();
      URL.revokeObjectURL(url);
    });
  }, []);

  // ── Code export: React ──

  const handleExportAsReact = useCallback(() => {
    safeExport('导出 React 组件', () => {
      if (!generatedHtml) return;
      const page = pages[currentPageIndex];
      const componentName = (page?.name || 'ProtoPage').replace(/[^a-zA-Z0-9]/g, '');
      const jsx = htmlToReactComponent(generatedHtml, componentName);
      const blob = new Blob([jsx], { type: 'text/javascript' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${componentName}.jsx`;
      a.click();
      URL.revokeObjectURL(url);
    });
  }, [generatedHtml, pages, currentPageIndex]);

  // ── Code export: Tailwind ──

  const handleExportAsTailwind = useCallback(() => {
    safeExport('导出 Tailwind', () => {
      if (!generatedHtml) return;
      const page = pages[currentPageIndex];
      const twHtml = htmlToTailwind(htmlToCleanHtml(generatedHtml, page?.name || 'ProtoAI'));
      const blob = new Blob([twHtml], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(page?.name || 'page').replace(/\s+/g, '_')}_tailwind.html`;
      a.click();
      URL.revokeObjectURL(url);
    });
  }, [generatedHtml, pages, currentPageIndex]);

  // ── Code export: Clean HTML ──

  const handleExportCleanHtml = useCallback(() => {
    safeExport('导出 Clean HTML', () => {
      if (!generatedHtml) return;
      const page = pages[currentPageIndex];
      const cleanHtml = htmlToCleanHtml(generatedHtml, page?.name || 'ProtoAI');
      const blob = new Blob([cleanHtml], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(page?.name || 'page').replace(/\s+/g, '_')}_clean.html`;
      a.click();
      URL.revokeObjectURL(url);
    });
  }, [generatedHtml, pages, currentPageIndex]);

  // ── Project export ──

  const handleExportProject = useCallback(() => {
    safeExport('导出项目', () => {
      const proj = currentProject;
      const exportData = {
        version: 1,
        type: 'protoai_project',
        exportedAt: new Date().toISOString(),
        project: proj,
      };
      const json = JSON.stringify(exportData, null, 2);
      const blob = new Blob([json], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(proj.name || 'project').replace(/[^a-zA-Z0-9\u4e00-\u9fff]/g, '_')}.protoai.json`;
      a.click();
      URL.revokeObjectURL(url);
    });
  }, [currentProject]);

  // ── Project import ──

  const handleImportProject = useCallback(() => {
    importInputRef.current?.click();
  }, []);

  const handleImportFile = useCallback((e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    e.target.value = '';

    const reader = new FileReader();
    reader.onload = (evt) => {
      try {
        const data = JSON.parse(evt.target.result);

        // Schema validation
        const validationError = validateProjectSchema(data);
        if (validationError) {
          alert(validationError);
          return;
        }

        const proj = data.project;
        // Sanitize: ensure arrays exist, strip unexpected fields
        const sanitized = {
          id: generateId(),
          name: (proj.name || '导入项目') + ' (导入)',
          contentDesc: typeof proj.contentDesc === 'string' ? proj.contentDesc : '',
          styleDesc: typeof proj.styleDesc === 'string' ? proj.styleDesc : '',
          selectedStyles: Array.isArray(proj.selectedStyles) ? proj.selectedStyles : ['business'],
          pages: Array.isArray(proj.pages) ? proj.pages.filter(Boolean) : [],
          history: Array.isArray(proj.history) ? proj.history : [],
          savedPlans: Array.isArray(proj.savedPlans) ? proj.savedPlans : [],
          loadedPlanId: proj.loadedPlanId || null,
          plannedPages: proj.plannedPages || null,
          plannedStyleSpec: typeof proj.plannedStyleSpec === 'string' ? proj.plannedStyleSpec : '',
          detectedPlatform: proj.detectedPlatform || 'pc',
          timestamp: Date.now(),
        };

        setProjects(prev => ({ ...prev, [sanitized.id]: sanitized }));
        setActiveProjectId(sanitized.id);
        setCurrentPageIndex(0);
        setCode(sanitized.pages[0]?.html || '');
        setMessages([]);
        setPlannedPages(sanitized.plannedPages);
        setPlannedStyleSpec(sanitized.plannedStyleSpec);
        setDetectedPlatform(sanitized.detectedPlatform);
        setIsGenerating(false);
        setIsRefining(false);
        setIsRegenerating(false);
        setPcPages(null);
        setMobilePages(null);
        setPcGeneratedPages(null);
        setMobileGeneratedPages(null);
        setActivePlanPlatform('pc');
        setGenerateError('');
        setGenerateProgress('');

        if (sanitized.pages.length > 0 && sanitized.pages.some(p => p?.html)) {
          setRightViewMode('prototype');
        } else if (sanitized.plannedPages?.length > 0) {
          const wfHtmls = generateAllWireframes(sanitized.plannedPages, sanitized.detectedPlatform || 'pc');
          setWireframeHtmls(wfHtmls);
          setRightViewMode('plan');
        } else {
          setWireframeHtmls([]);
          setRightViewMode('empty');
        }
      } catch (err) {
        alert('导入失败：文件解析错误 — ' + (err.message || ''));
      }
    };
    reader.readAsText(file);
  }, [setProjects, setActiveProjectId, setCurrentPageIndex, setCode, setMessages,
    setPlannedPages, setPlannedStyleSpec, setDetectedPlatform,
    setIsGenerating, setIsRefining, setIsRegenerating,
    setPcPages, setMobilePages, setPcGeneratedPages, setMobileGeneratedPages,
    setActivePlanPlatform, setGenerateError, setGenerateProgress,
    setWireframeHtmls, setRightViewMode]);

  // ── Refresh iframe ──

  const handleRefresh = useCallback(() => {
    if (!generatedHtml) return;
    const idx = currentPageIndex;
    const html = pagesRef.current[idx]?.html;
    if (!html) return;
    // Clear then restore to force iframe reload
    setPages((prev) => {
      const next = [...prev];
      if (next[idx]) next[idx] = { ...next[idx], html: '' };
      return next;
    });
    setTimeout(() => {
      setPages((prev) => {
        const next = [...prev];
        if (next[idx]) next[idx] = { ...next[idx], html };
        return next;
      });
    }, 50);
  }, [generatedHtml, currentPageIndex, setPages, pagesRef]);

  return {
    importInputRef,
    handleExport, handleExportAll,
    handleExportImage, handleExportAllImages,
    handleExportHistory,
    handleExportAsReact, handleExportAsTailwind, handleExportCleanHtml,
    handleExportProject, handleImportProject, handleImportFile,
    handleRefresh,
  };
}
