import { useCallback, useRef } from 'react';
import JSZip from 'jszip';
import { capturePageAsImage, injectNavigation, pageFileName } from '../aiService.js';
import { htmlToReactComponent, htmlToTailwind, htmlToCleanHtml } from '../codeExport.js';
import { generateAllWireframes } from '../components/PlanPreview.jsx';
import { generateId } from './useProjects.js';

export default function useExport({
  currentProject, projectName, pages, pagesRef, generatedHtml, currentPageIndex,
  setProjects, setActiveProjectId, setPages,
  setCurrentPageIndex, setCode, setMessages,
  setPlannedPages, setPlannedStyleSpec, setDetectedPlatform,
  setPcPages, setMobilePages, setActivePlanPlatform,
  setPcGeneratedPages, setMobileGeneratedPages,
  setWireframeHtmls, setRightViewMode,
  setGenerateProgress, setGenerateError,
  setIsGenerating, setIsRefining, setIsRegenerating,
}) {
  const importInputRef = useRef(null);

  // ── Export current page HTML ──

  const handleExport = useCallback(() => {
    try {
      if (!generatedHtml) return;
      const page = pages[currentPageIndex];
      const fileName = page?.name ? `${projectName || 'prototype'}_${page.name}.html` : `${projectName || 'prototype'}.html`;
      const blob = new Blob([generatedHtml], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = fileName; a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Export failed:', err);
    }
  }, [generatedHtml, projectName, pages, currentPageIndex]);

  // ── Export all pages as ZIP ──

  const handleExportAll = useCallback(async () => {
    try {
      const validPages = pages.filter((p) => p?.html);
      if (validPages.length === 0) return;
      if (validPages.length === 1) { handleExport(); return; }

      const pagesWithNav = injectNavigation(validPages);
      const zip = new JSZip();
      pagesWithNav.forEach((page, i) => {
        if (!page?.html) return;
        zip.file(pageFileName(page, i), page.html);
      });

      const pageLinks = pages.map((page, i) => {
        if (!page?.html) return '';
        const fn = pageFileName(page, i);
        return `<a href="${fn}" class="l"><span class="n">${page.name}</span>${page.description ? `<span class="d">${page.description}</span>` : ''}<span class="a">&rarr;</span></a>`;
      }).filter(Boolean).join('\n');

      const indexHtml = `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${projectName || 'ProtoAI Prototype'}</title><style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#fafafa;color:#111;padding:48px 24px}.c{max-width:640px;margin:0 auto}h1{font-size:28px;font-weight:700;margin-bottom:8px}p{font-size:14px;color:#888;margin-bottom:32px}.l{display:flex;align-items:center;gap:12px;padding:16px 20px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;text-decoration:none;color:#111;margin-bottom:8px;transition:all .15s}.l:hover{border-color:#1863dc;background:#f0f5ff}.n{font-weight:600;font-size:15px;flex-shrink:0}.d{flex:1;font-size:13px;color:#888;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.a{color:#ccc;font-size:18px;flex-shrink:0}.f{margin-top:48px;font-size:12px;color:#bbb;text-align:center}</style></head><body><div class="c"><h1>${projectName || 'ProtoAI Prototype'}</h1><p>共 ${validPages.length} 个页面</p>${pageLinks}<div class="f">Generated by ProtoAI</div></div></body></html>`;
      zip.file('index.html', indexHtml);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `${projectName || 'prototype'}.zip`; a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('ZIP export failed:', err);
      alert('导出 ZIP 失败：' + (err.message || '未知错误'));
    }
  }, [pages, projectName, handleExport]);

  // ── Export current page as image ──

  const handleExportImage = useCallback(async () => {
    if (!generatedHtml) return;
    try {
      setGenerateProgress('正在生成图片...');
      const blob = await capturePageAsImage(generatedHtml, 1440, 900);
      const page = pages[currentPageIndex];
      const fileName = page?.name ? `${projectName || 'prototype'}_${page.name}.png` : `${projectName || 'prototype'}.png`;
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = fileName; a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Image export failed:', err);
      alert('导出图片失败：' + (err.message || '请使用 HTML 导出'));
    } finally {
      setGenerateProgress('');
    }
  }, [generatedHtml, projectName, pages, currentPageIndex, setGenerateProgress]);

  // ── Export all pages as images ZIP ──

  const handleExportAllImages = useCallback(async () => {
    try {
      const validPages = pages.map((p, i) => ({ page: p, originalIndex: i })).filter(({ page }) => page?.html);
      if (validPages.length === 0) return;
      if (validPages.length === 1) { await handleExportImage(); return; }

      setGenerateProgress('正在生成图片...');
      const zip = new JSZip();

      for (let i = 0; i < validPages.length; i++) {
        setGenerateProgress(`正在生成图片 ${i + 1}/${validPages.length}...`);
        try {
          const blob = await capturePageAsImage(validPages[i].page.html, 1440, 900);
          const arrayBuf = await blob.arrayBuffer();
          zip.file(pageFileName(validPages[i].page, validPages[i].originalIndex).replace('.html', '.png'), arrayBuf);
        } catch (err) {
          console.warn(`Failed to capture page ${validPages[i].page.name}:`, err);
        }
      }

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `${projectName || 'prototype'}_images.zip`; a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Image ZIP export failed:', err);
      alert('导出图片 ZIP 失败：' + (err.message || '未知错误'));
    } finally {
      setGenerateProgress('');
    }
  }, [pages, projectName, handleExportImage, setGenerateProgress]);

  // ── Export from history ──

  const handleExportHistory = useCallback((entry, type) => {
    try {
      if (!entry?.pages) return;
      const validPages = entry.pages.filter((p) => p?.html);
      if (validPages.length === 0) return;

      if (type === 'html' && validPages.length === 1) {
        const blob = new Blob([validPages[0].html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `${entry.description || 'prototype'}.html`; a.click();
        URL.revokeObjectURL(url);
        return;
      }

      const zip = new JSZip();
      const pagesWithNav = injectNavigation(validPages);
      pagesWithNav.forEach((page, i) => {
        if (!page?.html) return;
        zip.file(pageFileName(page, i), page.html);
      });
      zip.generateAsync({ type: 'blob' }).then((blob) => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `${entry.description || 'prototype'}.zip`; a.click();
        URL.revokeObjectURL(url);
      });
    } catch (err) {
      console.error('History export failed:', err);
    }
  }, []);

  // ── Code export: React ──

  const handleExportAsReact = useCallback(() => {
    if (!generatedHtml) return;
    const page = pages[currentPageIndex];
    const componentName = (page?.name || 'ProtoPage').replace(/[^a-zA-Z0-9]/g, '');
    const jsx = htmlToReactComponent(generatedHtml, componentName);
    const blob = new Blob([jsx], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${componentName}.jsx`;
    a.click();
    URL.revokeObjectURL(url);
  }, [generatedHtml, pages, currentPageIndex]);

  // ── Code export: Tailwind ──

  const handleExportAsTailwind = useCallback(() => {
    if (!generatedHtml) return;
    const page = pages[currentPageIndex];
    const twHtml = htmlToTailwind(htmlToCleanHtml(generatedHtml, page?.name || 'ProtoAI'));
    const blob = new Blob([twHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(page?.name || 'page').replace(/\s+/g, '_')}_tailwind.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [generatedHtml, pages, currentPageIndex]);

  // ── Code export: Clean HTML ──

  const handleExportCleanHtml = useCallback(() => {
    if (!generatedHtml) return;
    const page = pages[currentPageIndex];
    const cleanHtml = htmlToCleanHtml(generatedHtml, page?.name || 'ProtoAI');
    const blob = new Blob([cleanHtml], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(page?.name || 'page').replace(/\s+/g, '_')}_clean.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [generatedHtml, pages, currentPageIndex]);

  // ── Project export ──

  const handleExportProject = useCallback(() => {
    try {
      const proj = currentProject;
      const exportData = {
        version: 1,
        type: 'protoai_project',
        exportedAt: new Date().toISOString(),
        project: proj,
      };
      const json = JSON.stringify(exportData, null, 2);
      const blob = new Blob([json], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${(proj.name || 'project').replace(/[^a-zA-Z0-9\u4e00-\u9fff]/g, '_')}.protoai.json`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Project export failed:', err);
      alert('导出项目失败：' + (err.message || '未知错误'));
    }
  }, [currentProject]);

  // ── Project import ──

  const handleImportProject = useCallback(() => {
    importInputRef.current?.click();
  }, []);

  const handleImportFile = useCallback((e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    e.target.value = '';

    const reader = new FileReader();
    reader.onload = (evt) => {
      try {
        const data = JSON.parse(evt.target.result);
        if (!data.project || data.type !== 'protoai_project') {
          alert('文件格式不正确，请选择 .protoai.json 文件');
          return;
        }
        const proj = data.project;
        const newId = generateId();
        const imported = { ...proj, id: newId, name: (proj.name || '导入项目') + ' (导入)' };
        setProjects(prev => ({ ...prev, [newId]: imported }));
        setActiveProjectId(newId);
        setCurrentPageIndex(0);
        setCode(imported.pages?.[0]?.html || '');
        setMessages([]);
        setPlannedPages(imported.plannedPages || null);
        setPlannedStyleSpec(imported.plannedStyleSpec || '');
        setDetectedPlatform(imported.detectedPlatform || 'pc');
        setIsGenerating(false);
        setIsRefining(false);
        setIsRegenerating(false);
        setPcPages(null);
        setMobilePages(null);
        setPcGeneratedPages(null);
        setMobileGeneratedPages(null);
        setActivePlanPlatform('pc');
        setGenerateError('');
        setGenerateProgress('');

        if (imported.pages?.length > 0 && imported.pages.some(p => p?.html)) {
          setRightViewMode('prototype');
        } else if (imported.plannedPages?.length > 0) {
          const wfHtmls = generateAllWireframes(imported.plannedPages, imported.detectedPlatform || 'pc');
          setWireframeHtmls(wfHtmls);
          setRightViewMode('plan');
        } else {
          setWireframeHtmls([]);
          setRightViewMode('empty');
        }
      } catch (err) {
        alert('导入失败：文件解析错误 — ' + (err.message || ''));
      }
    };
    reader.readAsText(file);
  }, [setProjects, setActiveProjectId, setCurrentPageIndex, setCode, setMessages,
    setPlannedPages, setPlannedStyleSpec, setDetectedPlatform,
    setIsGenerating, setIsRefining, setIsRegenerating,
    setPcPages, setMobilePages, setPcGeneratedPages, setMobileGeneratedPages,
    setActivePlanPlatform, setGenerateError, setGenerateProgress,
    setWireframeHtmls, setRightViewMode]);

  // ── Refresh iframe ──

  const handleRefresh = useCallback(() => {
    if (!generatedHtml) return;
    const idx = currentPageIndex;
    const html = pagesRef.current[idx]?.html;
    if (!html) return;
    // Clear then restore to force iframe reload
    setPages((prev) => {
      const next = [...prev];
      if (next[idx]) next[idx] = { ...next[idx], html: '' };
      return next;
    });
    setTimeout(() => {
      setPages((prev) => {
        const next = [...prev];
        if (next[idx]) next[idx] = { ...next[idx], html };
        return next;
      });
    }, 50);
  }, [generatedHtml, currentPageIndex, setPages, pagesRef]);

  return {
    importInputRef,
    handleExport, handleExportAll,
    handleExportImage, handleExportAllImages,
    handleExportHistory,
    handleExportAsReact, handleExportAsTailwind, handleExportCleanHtml,
    handleExportProject, handleImportProject, handleImportFile,
    handleRefresh,
  };
}
